LATEXCMD = pdflatex --shell-escape presentation.tex

thesis:
	$(LATEXCMD) && $(LATEXCMD)

fast:
	$(LATEXCMD)

clean:
	rm -rf *.aux *.bbl *.bcf *.blg *.lof *.log *.lot *.toc *.xml svg-inkscape *.pdf *.nav *.out *.snm
